#pragma once
namespace ally {
namespace error {
// ErrorTypes:
// FAT -> Fatal Error
// COM -> Compiler Error(Debug)
// ERR -> Error
// WAR -> Warn
// INF -> INFO
// ErrorPlace
// LEX -> Lexer
// PAR -> Parser
// SEM -> Semantic Analysis
// COD -> CodeGen
// ErrorType_ErrorPlace_Error
enum class Code {
  ERR_LEX_UNKNOWN_SYMBOL,
  ERR_PAR_UNKNOWN_EXPR_TOKEN,
  ERR_PAR_UNKNOWN_STMT_TOKEN,
  ERR_PAR_EXCEPTED_LPAREN_AFTER_FUNC,
  ERR_PAR_EXPECTED_RPAREN_AFTER_ARGS,
  ERR_PAR_EXPECTED_IDENTIFIER_VAR,
  ERR_SEM_MULTIPLE_FUNCTION_DECL,
  COM_SEM_FUNCTIONNODE_VISITED,
  COM_SEM_EXPECTED_EXPR,
  COM_SEM_NO_SCOPE_AVAILABLE,
  ERR_SEM_RETURN_UNEXPECTED_TYPE,
  ERR_SEM_SYMBOL_IS_NOT_VAR,
  ERR_SEM_VAR_MULTIPLE_DEFINED,
  ERR_SEM_VAR_NOT_MATCH_VALUE_TYPE,
  COM_MIR_NO_SCOPE_AVAILABLE,
  COM_MIR_EXPR_IS_NULL,
  COM_MIR_UNKNOWN_EXPR,
  COM_MIR_UNKNOWN_OPSTR,
  COM_MIR_STMT_IS_NULL,
  COM_MIR_UNKNOWN_STMT,
};
} // namespace error
} // namespace ally
